"""Refactor: Remove top_themes feature

Revision ID: 7aa9c9724ebb
Revises: a8bc56db2186
Create Date: 2025-10-25 11:21:39.771203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7aa9c9724ebb'
down_revision = 'a8bc56db2186'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_top_themes_csv_analysis_id', table_name='top_themes')
    op.drop_index('ix_top_themes_id', table_name='top_themes')
    op.drop_table('top_themes')
    op.drop_column('limits', 'top_themes_used')
    op.drop_column('limits', 'top_themes_total')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('limits', sa.Column('top_themes_total', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('limits', sa.Column('top_themes_used', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('top_themes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('csv_analysis_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('theme_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('sales_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revenue', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['csv_analysis_id'], ['csv_analyses.id'], name='top_themes_csv_analysis_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='top_themes_pkey')
    )
    op.create_index('ix_top_themes_id', 'top_themes', ['id'], unique=False)
    op.create_index('ix_top_themes_csv_analysis_id', 'top_themes', ['csv_analysis_id'], unique=False)
    # ### end Alembic commands ###
