"""add_avg_revenue_per_sale_to_analytics_reports

Revision ID: a8bc56db2186
Revises: e6e2ae948e16
Create Date: 2025-10-23 17:44:56.724759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bc56db2186'
down_revision = 'e6e2ae948e16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_reports', sa.Column('avg_revenue_per_sale', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics_reports', 'avg_revenue_per_sale')
    # ### end Alembic commands ###
