"""add_theme_cooldown_days_to_limits

Revision ID: b241e3487fd2
Revises: 7aa9c9724ebb
Create Date: 2025-10-26 17:37:05.105974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b241e3487fd2'
down_revision = '7aa9c9724ebb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('limits', sa.Column('theme_cooldown_days', sa.Integer(), nullable=False))
    op.add_column('llm_settings', sa.Column('theme_cooldown_minutes', sa.Integer(), server_default='10080', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_settings', 'theme_cooldown_minutes')
    op.drop_column('limits', 'theme_cooldown_days')
    # ### end Alembic commands ###
