"""Add analytics_message_ids to csv_analysis

Revision ID: e6e2ae948e16
Revises: restore_theme_requests_001
Create Date: 2025-10-21 20:47:41.151403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e2ae948e16'
down_revision = 'restore_theme_requests_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csv_analyses', sa.Column('analytics_message_ids', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csv_analyses', 'analytics_message_ids')
    # ### end Alembic commands ###
